package enumeration;

/**
 *
 * @author vitor
 */
public enum OperationType {
    CREATE_CLUSTER,
    DELETE_CLUSTER,
    INSERT_CONCEPTUAL_WORKFLOW,
    UPDATE_CONCEPTUAL_WORKFLOW,
    DELETE_CONCEPTUAL_WORKFLOW,
    SUBMIT_EXECUTION_WORKFLOW,
    RUN_EXECUTION_WORKFLOW,
    DELETE_EXECUTION_WORKFLOW,
    MONITOR_EXECUTION_WORKFLOW,
    RUN_QUERY,
    ABORT_MOUNTED_FOLDERS,
    UNKNOWN,
    DEBUG
}
